<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AllActiveMataKuliahSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // S1 PETERNAKAN GENAP
            [
                "kode_mata_kuliah" => "UMCY211",
                "nama_mata_kuliah" => "AIK",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCX232",
                "nama_mata_kuliah" => "Bahasa Inggris",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCX213",
                "nama_mata_kuliah" => "Kewarganegaraan",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX221",
                "nama_mata_kuliah" => "Ilmu Tilik Ternak",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX222",
                "nama_mata_kuliah" => "Fisiologi ternak",
                "sks" => 3,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX223",
                "nama_mata_kuliah" => "Agrostologi",
                "sks" => 3,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX224",
                "nama_mata_kuliah" => "Biokimia",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX225",
                "nama_mata_kuliah" => "Mikrobiologi",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX226",
                "nama_mata_kuliah" => "Statistika",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY411",
                "nama_mata_kuliah" => "AIK 2 (AL-Islam Studi AL-Hadist)",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX421",
                "nama_mata_kuliah" => "Pemuliaan Ternak",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY431",
                "nama_mata_kuliah" => "Aplikasi Komputer",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX431",
                "nama_mata_kuliah" => "Dasar Teknologi Hasil Ternak",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY432",
                "nama_mata_kuliah" => "Teknologi Fabrikasi Pakan",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX422",
                "nama_mata_kuliah" => "Tata Niaga Peternakan",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY422",
                "nama_mata_kuliah" => "Ekonomi Pembangunan",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY433",
                "nama_mata_kuliah" => "Penyuluhan dan Komunikasi",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY611",
                "nama_mata_kuliah" => "Kajian Islam Profesi",
                "sks" => 1,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY641",
                "nama_mata_kuliah" => "Etika Profesi",
                "sks" => 2,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX631",
                "nama_mata_kuliah" => "Manaj Ternak Unggas",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX632",
                "nama_mata_kuliah" => "Minaj Ternak Perah",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX633",
                "nama_mata_kuliah" => "Manaj Ternak Potong",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX123",
                "nama_mata_kuliah" => "Rancangan Percobaan (Rancob)",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AX234",
                "nama_mata_kuliah" => "Studi Kelayakan Proyek",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY763",
                "nama_mata_kuliah" => "Budidaya Satwa harapan",
                "sks" => 2,
                "semester" => 8,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY761",
                "nama_mata_kuliah" => "Pengelolaan penetasan",
                "sks" => 2,
                "semester" => 8,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY764",
                "nama_mata_kuliah" => "manajemen domba dan kambing",
                "sks" => 2,
                "semester" => 8,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY766",
                "nama_mata_kuliah" => "Ekonomi Perusahaan",
                "sks" => 2,
                "semester" => 8,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1AY768",
                "nama_mata_kuliah" => "Nutrisi ternak unggas dan non ruminant",
                "sks" => 2,
                "semester" => 8,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 1,
                "is_active" => "1",
                "max_peserta" => null,
            ],

            // S1 TEKNIK INDUSTRI GENAP
            [
                "kode_mata_kuliah" => "UMCY211",
                "nama_mata_kuliah" => "AIK 1",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX132",
                "nama_mata_kuliah" => "Bahasa Pemrograman Komputer",
                "sks" => 3,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX222",
                "nama_mata_kuliah" => "Fisika & Alat Ukur",
                "sks" => 3,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX212",
                "nama_mata_kuliah" => "Kalkulus ",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX221",
                "nama_mata_kuliah" => "Kimia Industri",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX224",
                "nama_mata_kuliah" => "Organisasi Dan Manajemen Perusahaan Industri",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX211",
                "nama_mata_kuliah" => "Pendidikan Kewarganegaraan",
                "sks" => 1,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX223",
                "nama_mata_kuliah" => "Teori Peluang",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY411",
                "nama_mata_kuliah" => "Al Islam Studi Al Hadist",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX421",
                "nama_mata_kuliah" => "Mekanika Teknik",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX333",
                "nama_mata_kuliah" => "Statistika Industri",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX431",
                "nama_mata_kuliah" => "Optimasi",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX432",
                "nama_mata_kuliah" => "Proses Produksi I",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX433",
                "nama_mata_kuliah" => "Akuntansi Biaya",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX434",
                "nama_mata_kuliah" => "Ergonomi Industri",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX441",
                "nama_mata_kuliah" => "Manajemen Sumber Daya Manusia",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY611",
                "nama_mata_kuliah" => "Kajian Islam Profesi",
                "sks" => 1,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY641",
                "nama_mata_kuliah" => "Etika Profesi",
                "sks" => 2,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX631",
                "nama_mata_kuliah" => "Ekonomi Teknik",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX632",
                "nama_mata_kuliah" => "Pemodelan Sistem",
                "sks" => 2,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BY631",
                "nama_mata_kuliah" => "Manajemen Proyek",
                "sks" => 2,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BY632",
                "nama_mata_kuliah" => "Sistem Produksi",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BX641",
                "nama_mata_kuliah" => "Psikologi Industri",
                "sks" => 2,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BY762",
                "nama_mata_kuliah" => "Sistem Manufaktur Fleksibel",
                "sks" => 2,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BY661",
                "nama_mata_kuliah" => "Supply Chain Management",
                "sks" => 2,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1BY761",
                "nama_mata_kuliah" => "Sistem Perawatan",
                "sks" => 2,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 2,
                "is_active" => "1",
                "max_peserta" => null,
            ],

            // S1 TEKNIK INFORMATIKA GENAP
            [
                "kode_mata_kuliah" => "UMCY211",
                "nama_mata_kuliah" => "Al Islam Studi Kemuhammadiyahan",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY241",
                "nama_mata_kuliah" => "Kewirausahaan Islami (Islamic Entrepreuneurship)",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCX113",
                "nama_mata_kuliah" => "Bahasa Indonesia / Tata Tulis Karya Ilmiah",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCX112",
                "nama_mata_kuliah" => "Kewarganegaraan",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX123",
                "nama_mata_kuliah" => "Kalkulus  I (Calculus I)",
                "sks" => 2,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX322",
                "nama_mata_kuliah" => "Sistem Digital (Digital System)",
                "sks" => 3,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX222",
                "nama_mata_kuliah" => "Sistem Operasi (Operating System)",
                "sks" => 3,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX231",
                "nama_mata_kuliah" => "Pemrograman I (Terstruktur) (Structured Programming)",
                "sks" => 3,
                "semester" => 2,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY411",
                "nama_mata_kuliah" => "Al Islam Studi Al Hadist",
                "sks" => 2,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX426",
                "nama_mata_kuliah" => "Analisis & Strategi Algortma",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX425",
                "nama_mata_kuliah" => "Matematika Diskrit (Discrete Mathematics)",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX532",
                "nama_mata_kuliah" => "Jaringan Komputer (Computer Network)",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX541",
                "nama_mata_kuliah" => "Rekayasa Perangkat Lunak (Software Engineering)",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX431",
                "nama_mata_kuliah" => "Pemrograman IV (PBO Lanjut) (Advanced Object Oriented Programming)",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX432",
                "nama_mata_kuliah" => "Basis Data (Relational Data Base)",
                "sks" => 3,
                "semester" => 4,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY611",
                "nama_mata_kuliah" => "Kajian Islam Profesi",
                "sks" => 1,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX332",
                "nama_mata_kuliah" => "Pemrograman III (Visual) (Visual Programming)",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CY669",
                "nama_mata_kuliah" => "Sistem Paralel dan Terdistribusi",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX632",
                "nama_mata_kuliah" => "Kecerdasan Komputasional (Computational Intelligence)",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX643",
                "nama_mata_kuliah" => "Analisis dan Perancangan Berorientasi Objek (Object Oriented Analysis and Design)",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CX641",
                "nama_mata_kuliah" => "Pengamanan Sistem Komputer (Computer Security System)",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "C1CY768",
                "nama_mata_kuliah" => "PEMROGRAMAN WEB LANJUT (MK PILIHAN)",
                "sks" => 3,
                "semester" => 6,
                "paket" => "Genap",
                "sifat" => "Pilihan",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ],
            [
                "kode_mata_kuliah" => "UMCY641",
                "nama_mata_kuliah" => "Etika Profesi",
                "sks" => 2,
                "semester" => 8,
                "paket" => "Genap",
                "sifat" => "Wajib",
                "id_prodi" => 3,
                "is_active" => "1",
                "max_peserta" => null,
            ]
        ];

        $this->db->table('mata_kuliah')->insertBatch($data);
    }}
